In [53]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

## 1D Array

In [2]:
a=np.array([10,20,30,50,60,0])

In [3]:
a.dtype

dtype('int32')

In [4]:
a.shape

(6,)

In [5]:
a.ndim

1

In [6]:
a.size

6

In [7]:
a[0]

10

In [8]:
a[2]

30

## Multi dimensional array

In [9]:
a_2d=np.array([[10,20,30],[23,55,15]])
a_2d

array([[10, 20, 30],
       [23, 55, 15]])

In [10]:
a_2d.dtype

dtype('int32')

In [11]:
a_2d.shape

(2, 3)

In [12]:
a_2d.ndim

2

In [13]:
a_2d.size

6

In [14]:
a_2d[0]

array([10, 20, 30])

## Another type of multi dimesional array

In [15]:
another_type_array=np.array([[[1,2,3,4]]])
another_type_array

array([[[1, 2, 3, 4]]])

In [16]:
another_type_array.shape

(1, 1, 4)

In [17]:
another_type_array.ndim

3

### First element in first array

In [18]:
a_2d[0][0]

10

### second element in second array

In [19]:
a_2d[1][1]

55

### Lets change its data type into float

In [20]:
a_2d=np.array([[10,20,30],[23,55,15]], dtype=float)
a_2d

array([[10., 20., 30.],
       [23., 55., 15.]])

## Lets create a bigger array

In [21]:
a_bigger=np.array([
    [
        [10,20,30,40],[8,8,2,1],[1,1,1,2]
    ],
    [
        [9,9,2,39],[1,2,3,3],[0,0,3,2]
    ],
    [
        [12,33,22,1],[22,1,22,2],[0,2,3,1]
    ]
],dtype=float)

In [22]:
a_bigger.shape

(3, 3, 4)

In [23]:
a_bigger.ndim

3

In [24]:
a_bigger.size

36

In [25]:
a_bigger[2][2][3]

1.0

In [26]:
a_bigger[2][2]

array([0., 2., 3., 1.])

## Filling arrays
#### np.full
##### By using the full function for eg we fill an array of a certain shape with the same number

In [27]:
a_full=np.full((3,5,4),7)
a_full

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [28]:
a_full.ndim

3

## Zeros and ones
#### for the case that we want arrays full of zeros or ones, we even have specific functions

In [29]:
a_zeros=np.zeros((3,3))
a_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
b_ones=np.ones((2,3,4))
b_ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [31]:
b_ones.ndim

3

## Empty and random
#### other options would be to create an empty array or one that is filled with random numbers.

In [32]:
e=np.empty((4,4))
e

array([[4.67296746e-307, 1.69121096e-306, 2.33646845e-307,
        1.11256817e-306],
       [1.06811422e-306, 1.42417221e-306, 1.11260619e-306,
        8.90094053e-307],
       [1.86919378e-306, 1.06809792e-306, 1.37962456e-306,
        1.69111861e-306],
       [1.78020169e-306, 1.37961777e-306, 7.56599807e-307,
        7.56599806e-307]])

In [33]:
b_random=np.random.random((2,2))
b_random

array([[0.06591557, 0.2607384 ],
       [0.14838013, 0.47918526]])

In [34]:
b_random.ndim

2

In [35]:
b_random.size

4

## RANGES
#### Instead of filling array with same values,we can fill create sequences of values by specifying the boundaries.
### arange    
#### arguments(start,stop,step)

In [36]:
a_arange=np.arange(10,50,5)
a_arange

array([10, 15, 20, 25, 30, 35, 40, 45])

### linspace
#### by using linspace we also create a list from a minimum value to a maximum value. But instead of specifying the step size we specify the amount of values that we want to have in our list.They will all be spread evenly and have the same distance to their neighbours
##### start-stop-number of values

In [37]:
b_linspace=np.linspace(0,50,2)
b_linspace

array([ 0., 50.])

In [38]:
b_linspace.ndim

1

In [39]:
b_linspace.size

2

In [40]:
b_linspace1=np.linspace(0,50,25)
b_linspace1

array([ 0.        ,  2.08333333,  4.16666667,  6.25      ,  8.33333333,
       10.41666667, 12.5       , 14.58333333, 16.66666667, 18.75      ,
       20.83333333, 22.91666667, 25.        , 27.08333333, 29.16666667,
       31.25      , 33.33333333, 35.41666667, 37.5       , 39.58333333,
       41.66666667, 43.75      , 45.83333333, 47.91666667, 50.        ])

In [41]:
b_linspace1.size

25

In [42]:
b_linspace2=np.linspace(0,50,25,dtype=int)
b_linspace2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 50])

## Math functions and Aggregate function

In [43]:
np.median(b_linspace2)

25.0

In [44]:
np.sum(b_linspace2)

614

In [45]:
np.sqrt(b_linspace2)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
       4.47213595, 4.69041576, 5.        , 5.19615242, 5.38516481,
       5.56776436, 5.74456265, 5.91607978, 6.08276253, 6.244998  ,
       6.40312424, 6.55743852, 6.70820393, 6.8556546 , 7.07106781])

In [46]:
np.std(b_linspace2)

14.924020905908701

In [47]:
np.cos(b_linspace2)

array([ 1.        , -0.41614684, -0.65364362,  0.96017029, -0.14550003,
       -0.83907153,  0.84385396,  0.13673722, -0.95765948,  0.66031671,
        0.40808206, -0.99996083,  0.99120281, -0.29213881, -0.74805753,
        0.91474236, -0.01327675, -0.90369221,  0.76541405,  0.26664293,
       -0.98733928,  0.5551133 ,  0.52532199, -0.99233547,  0.96496603])

In [48]:
np.exp(b_linspace2)

array([1.00000000e+00, 7.38905610e+00, 5.45981500e+01, 4.03428793e+02,
       2.98095799e+03, 2.20264658e+04, 1.62754791e+05, 1.20260428e+06,
       8.88611052e+06, 6.56599691e+07, 4.85165195e+08, 3.58491285e+09,
       7.20048993e+10, 5.32048241e+11, 3.93133430e+12, 2.90488497e+13,
       2.14643580e+14, 1.58601345e+15, 1.17191424e+16, 8.65934004e+16,
       6.39843494e+17, 4.72783947e+18, 3.49342711e+19, 2.58131289e+20,
       5.18470553e+21])

In [49]:
np.sin(b_linspace2)

array([ 0.        ,  0.90929743, -0.7568025 , -0.2794155 ,  0.98935825,
       -0.54402111, -0.53657292,  0.99060736, -0.28790332, -0.75098725,
        0.91294525, -0.00885131, -0.13235175,  0.95637593, -0.66363388,
       -0.40403765,  0.99991186, -0.42818267, -0.64353813,  0.96379539,
       -0.15862267, -0.83177474,  0.85090352,  0.12357312, -0.26237485])

In [50]:
np.cos(b_linspace2)

array([ 1.        , -0.41614684, -0.65364362,  0.96017029, -0.14550003,
       -0.83907153,  0.84385396,  0.13673722, -0.95765948,  0.66031671,
        0.40808206, -0.99996083,  0.99120281, -0.29213881, -0.74805753,
        0.91474236, -0.01327675, -0.90369221,  0.76541405,  0.26664293,
       -0.98733928,  0.5551133 ,  0.52532199, -0.99233547,  0.96496603])

In [51]:
np.tan(b_linspace2)

array([ 0.00000000e+00, -2.18503986e+00,  1.15782128e+00, -2.91006191e-01,
       -6.79971146e+00,  6.48360827e-01, -6.35859929e-01,  7.24460662e+00,
        3.00632242e-01, -1.13731371e+00,  2.23716094e+00,  8.85165604e-03,
       -1.33526407e-01, -3.27370380e+00,  8.87142844e-01, -4.41695568e-01,
       -7.53130148e+01,  4.73814720e-01, -8.40771255e-01,  3.61455441e+00,
        1.60656699e-01, -1.49838734e+00,  1.61977519e+00, -1.24527568e-01,
       -2.71900612e-01])

In [54]:
np.log(b_linspace2)

array([      -inf, 0.69314718, 1.38629436, 1.79175947, 2.07944154,
       2.30258509, 2.48490665, 2.63905733, 2.77258872, 2.89037176,
       2.99573227, 3.09104245, 3.21887582, 3.29583687, 3.36729583,
       3.4339872 , 3.49650756, 3.55534806, 3.61091791, 3.66356165,
       3.71357207, 3.76120012, 3.80666249, 3.8501476 , 3.91202301])

In [55]:
b_linspace2.sum()

614

In [56]:
b_linspace2.min()

0

In [57]:
b_linspace2.max()

50

In [58]:
b_linspace2.mean()

24.56

In [59]:
b_linspace2.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'